package me.damoebe.architectures.transformer.mha;

import me.damoebe.architectures.mlp.structure.Connection;
import me.damoebe.architectures.transformer.embedding.Embedding;
import me.damoebe.architectures.transformer.embedding.Matrix;
import me.damoebe.architectures.transformer.embedding.Sequence;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A container class for Heads
 * @param <H> The type of head that is used stored in the class
 */
public class MultiHeadAttention<H extends Head> implements Cloneable{
    /**
     * A list of all heads that are contained in a MultiHeadAttention object
     */
    private final List<H> heads = new ArrayList<>();

    /**
     * A weight matrix that is used to convert the concat-heads-matrix into a matrix with the dimensions of the
     * input embedding-list
     */
    private final double[][] weights;

    /**
     * The last output sequence generated by this mha
     */
    private List<double[][]> currentHeadOutputs;
    private final double learningRate;

    /**
     * Main constructor for the MultiHeadAttention class
     * @param c The class that is being used for the heads
     * @param headAmount The amount of heads this MHA object should have
     * @param inputEmbeddingAmount The amount of the input embeddings
     * @param inputEmbeddingSize The size of the input embeddings
     */
    public MultiHeadAttention(Class<H> c, int headAmount, int inputEmbeddingAmount, int inputEmbeddingSize, boolean masked, double learningRate)  {
        this.learningRate = learningRate;
        // initialize heads
        try {
            Constructor<H> headConstructor = c.getConstructor(int.class, int.class, boolean.class);
            for (int h = 0; h != headAmount; h++) {
                H head;
                head = headConstructor.newInstance((inputEmbeddingAmount/headAmount), inputEmbeddingSize, masked);
                this.heads.add(head);
            }
        }catch (Exception e){
            throw new RuntimeException("H typed Class could not be loaded: " + e.getMessage());
        }

        // initialize weights ()
        this.weights = new double[inputEmbeddingSize][inputEmbeddingAmount];
        for (int row = 0; row != inputEmbeddingSize; row++){
            for (int column = 0; column != inputEmbeddingAmount; column++){
                weights[row][column] = Connection.getRandomWeight();
            }
        }
    }

    /**
     * Generates an output for a list of inputs(embedding lists).
     * @param input An input as a list of embedding lists -> see EDHead doc if you are using a list size larger than 1
     * @return The output embedding list
     */
    public Sequence generateOutputFor(Sequence[] input){
        List<double[][]> matrices = getHeadOutputMatrices(input);
        this.currentHeadOutputs = matrices;
        Sequence resultEmbeddings = new Sequence();
        double[][] outputMatrix = Matrix.multiply(concatMatrices(matrices), weights);
        for (int row = 0; row != Objects.requireNonNull(outputMatrix).length; row++){
            List<Double> embeddingData = new ArrayList<>();
            for (int column = 0; column != outputMatrix[0].length; column++){
                embeddingData.add(outputMatrix[row][column]);
            }
            resultEmbeddings.embeddings().add(new Embedding(embeddingData));
        }

        return resultEmbeddings;
    }

    /**
     * Splits the input into subsequences and inserts them in all heads. It also gets their outputs.
     * @param input The input Sequences for this mha
     * @return All output matrices in a list
     */
    private List<double[][]> getHeadOutputMatrices(Sequence[] input){
        List<double[][]> matrices = new ArrayList<>();
        int subSequence = 0;
        for (H head : heads){
            try {
                Sequence[] headInput = new Sequence[input.length];
                for (int s = 0; s != input.length; s++){
                    headInput[s] = input[s].getSubSequences(heads.size()).get(subSequence);
                }
                head.insertInput(headInput);
            }catch (Exception e){
                throw new RuntimeException(e.getMessage());
            }
            matrices.add(head.getOutput());
            subSequence++;
        }
        return matrices;
    }

    /**
     * Merges a list of matrices.
     * @param matrices the matrices that will be concat
     * @return the merged matrix as a 2d array
     */
    public static double[][] concatMatrices(List<double[][]> matrices){
        int rows = matrices.getFirst().length;
        int columns = 0;

        for (double[][] matrix : matrices){
            columns += matrix[0].length;
        }

        double[][] result = new double[rows][columns];

        int columnOffset = 0;

        for (double[][] matrix : matrices){
            for(int row = 0; row < rows; row++){
                System.arraycopy(matrix[row], 0, result[row], columnOffset, matrix[0].length);
            }
            columnOffset += matrix[0].length;
        }

        return result;
    }

    /**
     * Updates All head QKV weights as well as the weights which are used to merge the head matrices
     * @param deltas The first hidden-layer deltas of the block's mlp
     */
    public void updateAllWeights(double[][] deltas){
        updateWeights(deltas);
        List<double[][]> headDeltas = generateHeadDeltas(deltas);
        for (int headIndex = 0; headIndex != heads.size(); headIndex++){
            heads.get(headIndex).updateQKVWeights(headDeltas.get(headIndex), learningRate);
        }
    }

    /**
     * Updates the weights in the MultiHeadAttention class
     * @param deltas The deltas that are being inserted into this mha sub-layer (They must have horizontal sequence
     *               dimensions, like the weights)
     */
    private void updateWeights(double[][] deltas){
        if ((deltas.length != weights.length) && (deltas[0].length != weights[0].length)) return;
        // calculate deltas for mha weights
        double[][] concatHeadOutputs = concatMatrices(currentHeadOutputs);
        double[][] mhaDeltas = Matrix.multiply(concatHeadOutputs, deltas);
        // update mha weights based on mhaDeltas
        for (int weightRow = 0; weightRow != weights.length; weightRow++){
            for (int weightColumn = 0; weightColumn != weights[0].length; weightColumn++){
                assert mhaDeltas != null;
                weights[weightRow][weightColumn] -= learningRate * mhaDeltas[weightRow][weightColumn];
            }
        }
    }

    /**
     * Generates a list of head deltas that are passed into the heads at backpropagation
     * @param deltas The deltas of the next sub layer
     * @return The list containing the head deltas as matrices
     */
    private List<double[][]> generateHeadDeltas(double[][] deltas){
        if (deltas == null) return null;
        List<double[][]> headDeltaMatrices = new ArrayList<>();
        double[][] concatHeadDeltas = Matrix.multiply(weights, deltas);
        for (int headIndex = 0; headIndex != heads.size(); headIndex++){
            double[][] headDeltas = new double[heads.getFirst().inputEmbeddingAmount][heads.getFirst().inputEmbeddingSize];
            for (int headEmbedding = 0; headEmbedding != heads.getFirst().inputEmbeddingAmount; headEmbedding++){
                for (int embeddingData = 0; embeddingData != heads.getFirst().inputEmbeddingSize; embeddingData++){
                    assert concatHeadDeltas != null;
                    headDeltas[headEmbedding][embeddingData] = concatHeadDeltas[embeddingData][headIndex*heads.getFirst().inputEmbeddingAmount +
                            headEmbedding];
                }
            }
            headDeltaMatrices.add(headDeltas);
        }
        return headDeltaMatrices;
    }

    /**
     * Clones a MultiHeadAttention object.
     * @return The cloned object.
     */
    public MultiHeadAttention<H> clone(){
        try {
            //noinspection unchecked
            return (MultiHeadAttention<H>) super.clone();
        }catch (Exception e){
            throw new RuntimeException(e.getMessage());
        }
    }

    /**
     * Getter for the used embedding amount of this MHA.
     * @return The embedding Amount
     */
    public int getEmbeddingAmount(){
        return this.heads.getFirst().inputEmbeddingAmount;
    }

    /**
     * Getter for the used embedding size of this MHA.
     * @return the embedding size.
     */
    public int getEmbeddingSize(){
        return this.heads.getFirst().inputEmbeddingSize;
    }

    /**
     * Getter for the heads stored in the MultiHeadAttention
     * @return A list of the heads.
     */
    public List<H> getHeads(){
        return this.heads;
    }
}
